artifact_location: file:///C:/klasss/archive/OneOME_newts/runs/mlflow/603923395332083467
creation_time: 1748699692166
experiment_id: '603923395332083467'
last_update_time: 1748699692166
lifecycle_stage: active
name: C:/klasss/archive/newts/keypoints_dop
