artifact_uri: file:///C:/klasss/archive/OneOME_newts/runs/mlflow/603923395332083467/8ccd3925b20042a095920d3f6fabfed8/artifacts
end_time: null
entry_point_name: ''
experiment_id: '603923395332083467'
lifecycle_stage: active
run_id: 8ccd3925b20042a095920d3f6fabfed8
run_name: lizard_belly_keypoints22
run_uuid: 8ccd3925b20042a095920d3f6fabfed8
source_name: ''
source_type: 4
source_version: ''
start_time: 1748709892193
status: 1
tags: []
user_id: Ucer
