artifact_uri: file:///C:/klasss/archive/OneOME_newts/runs/mlflow/603923395332083467/40f4582052d34f369c3b4e3fae5a18de/artifacts
end_time: null
entry_point_name: ''
experiment_id: '603923395332083467'
lifecycle_stage: active
run_id: 40f4582052d34f369c3b4e3fae5a18de
run_name: lizard_belly_keypoints2
run_uuid: 40f4582052d34f369c3b4e3fae5a18de
source_name: ''
source_type: 4
source_version: ''
start_time: 1748706864354
status: 1
tags: []
user_id: Ucer
